#SPDX-License-Identifier: MIT-0
---
# vars file for solr

xwiki_keyring_path: "/usr/share/keyrings/xwiki-keyring.gpg"
xwiki_repo_key_url: "https://maven.xwiki.org/xwiki-keyring.gpg"
xwiki_repo_url: "deb https://maven.xwiki.org stable/"
